//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EvoXDTSR.rc
//
#define IDD_DLG_MAIN                    101
#define IDR_MAIN_MENU                   103
#define IDD_DLG_SETTINGS                104
#define IDD_DLG_ABOUT                   105
#define IDR_SEARCH_POPUP                110
#define IDD_DLG_QUEUE                   111
#define IDD_DLG_BPWIN                   112
#define IDR_ACCEL_MAIN                  113
#define IDD_DLG_DUMPWIN                 114
#define IDD_DLG_NEWBP                   117
#define IDR_BREAK_POPUP                 118
#define IDB_BITMAP_BPLIST               119
#define IDR_QUEUE_BUTMENU               120
#define IDD_DLG_LOGWIN                  121
#define IDR_MENU_BPHIST                 122
#define IDI_ICON1                       123
#define IDC_CMB_BPTYPE                  1002
#define IDC_BUT_POKE                    1010
#define IDC_BUT_SEARCH                  1011
#define IDC_BUT_CLEAR                   1012
#define IDC_BUT_DUMP                    1013
#define IDC_EDIT_MEMADDY                1014
#define IDC_EDIT_MEMPARAM               1015
#define IDC_EDIT_LOG                    1020
#define IDC_IPADDRESS                   1021
#define IDC_EDIT_LOGPATH                1022
#define IDC_BUT_LOGPATH                 1023
#define IDC_CHECK_LOG                   1024
#define IDC_STATIC_RELEASE              1026
#define IDC_EDIT_QUEUE_CMDS             1029
#define IDC_BUT_CMDS_EXECUTE            1030
#define IDC_BUT_CMDS_CANCEL             1031
#define IDC_BUT_QUEUE_CLEAR             1032
#define IDC_EDIT_BPWIN_EBP              1033
#define IDC_EDIT_BPWIN_EAX              1034
#define IDC_EDIT_BPWIN_EDX              1035
#define IDC_EDIT_BPWIN_EBX              1036
#define IDC_EDIT_BPWIN_ECX              1037
#define IDC_EDIT_BPWIN_ESI              1038
#define IDC_EDIT_BPWIN_EDI              1039
#define IDC_BUT_BPWIN_OK                1044
#define IDC_LIST_BPHIST                 1045
#define IDC_BUT_BPWIN_UNFREEZE          1046
#define IDC_LIST_DWIN_DHIST             1047
#define IDC_COMBO_FIRSTDUMP             1049
#define IDC_COMBO_DWIN_SECONDDUMP       1050
#define IDC_BUT_DWIN_COMPARE            1051
#define IDC_BUT_DWIN_OKAY               1055
#define IDC_RADIO_BOREVERSED            1056
#define IDC_RADIO_BONORMAL              1057
#define IDC_CHECK_MULTIPROMPT           1058
#define IDC_EDIT_LOGCAP                 1059
#define IDC_LIST_MEM                    1066
#define IDC_LIST_BP                     1067
#define IDC_CHECK_SHOWSCREENLOG         1068
#define IDC_EDIT_NEWBP_OFFSET           1069
#define IDC_RADIO_BYTE                  1071
#define IDC_RADIO_WORD                  1072
#define IDC_RADIO_DWORD                 1073
#define IDC_RADIO_WRITE                 1074
#define IDC_RADIO_READWRITE             1075
#define IDC_RADIO_EXECUTE               1076
#define IDC_SPIN_BPNUM                  1077
#define IDC_EDIT_BPNUM                  1078
#define IDC_BUT_NEWBP_OK                1079
#define IDC_BUT_NEWBP_CANCEL            1080
#define IDC_STATIC_SLOTORDIS            1081
#define IDC_CHECK_ENABLED               1082
#define IDC_LIST_REGISTERS              1083
#define IDC_BUT_QUEUE_MENU              1084
#define IDC_STATIC_MEMGROUP             1085
#define IDC_STATIC_BREAKGROUP           1086
#define IDC_STATIC_LASTLINE             1089
#define IDC_BUT_BPWIN_FREEZE            1090
#define IDC_EDIT_AUTOUNFREEZE           1092
#define IDC_CHECK_AUTOUNFREEZE          1093
#define IDC_STATIC_BREAKS               1094
#define IDC_STATIC_FOR                  1095
#define ID_APP_SETTINGS                 40001
#define ID_FUNCTIONS_CONNECT            40003
#define ID_FUNCTIONS_DISCONNECT         40004
#define ID_HELP_QUICKRUNDOWN            40006
#define ID_HELP_ABOUT                   40007
#define ID_FUNCTIONS_SAVEBUFFER         40008
#define ID_FUNCTIONS_FREEZE             40010
#define ID_FUNCTIONS_UNFREEZE           40011
#define ID_FUNCTIONS_RESET              40012
#define ID_RESET_HARD                   40013
#define ID_RESET_SOFT                   40014
#define ID_COPY_BREAKPOINTADDRESS       40019
#define ID_COPY_CURRENT                 40020
#define ID_COPY_ZERO                    40021
#define ID_COPY_ONE                     40022
#define ID_COPY_TWO                     40023
#define ID_COPY_THREE                   40024
#define ID_SRCH_REMOVE_ITEM             40030
#define ID_SRCH_CLEAR_LIST              40031
#define ID_SRCH_COPY_MEMORYOFFSET       40032
#define ID_SRCH_COPY_CLIPBOARD          40033
#define ID_COPY_MEMORYADDRESS           40040
#define ID_FUNCTIONS_CLEARSCREEN        40051
#define ID_FUNCTIONS_QUEUECOMMANDS      40052
#define ID_FUNCTIONS_CLEAR              40053
#define ID_FUNCTIONS_CLEARFILE          40056
#define ID_APP_EXITAPP                  40060
#define ID_SETTINGS_WINDOW              40061
#define ID_SETTINGS_                    40062
#define ID_SETTINGS_QUICKSETTINGS       40063
#define ID_SETTINGS_LOG                 40064
#define ID_SETTINGS_AUTO                40065
#define ID_HELP_CONTENTS                40069
#define ID_SETTINGS_FILELOG             40072
#define ID_SETTINGS_AUTOFREEZE          40073
#define ID_SETTINGS_SHOWLOG             40074
#define ID_SEARCHPOPUP_POKE             40077
#define ID_SEARCHPOPUP_DUMP             40078
#define ID_SRCH_SETBP                   40087
#define ID_BPPOPUP_MODIFY               40088
#define ID_BPPOPUP_CLEAR                40089
#define ID_BPPOPUP_CLEARALL             40090
#define ID_BPPOPUP_LIST                 40091
#define ID_BPPOPUP_STATUS               40092
#define ID_BPPOPUP_STAT_DISABLE         40097
#define ID_BPPOPUP_STAT_ENABLE          40098
#define ID_APP_DUMPWINDOW               40099
#define ID_QUEUEPOPUP_SAVE              40100
#define ID_QUEUEPOPUP_LOAD              40101
#define ID_SEARCHPOPUP_NEWSEARCH        40102
#define ID_SETTINGS_MENU                40103
#define ID_HELP_MENU                    40104
#define ID_SETTINGS_ONTOP               40105
#define ID_BPHISTPOP_REMOVEALL          40110
#define ID_BPHISTPOP_REMOVE             40111
#define ID_BPHISTPOP_COPYITEM           40112
#define ID_BPHISTPOP_COPYROW            40113
#define ID_APP_LOGWINDOW                40114
#define ID_APP_BPHISTORYWINDOW          40115
#define ID_APP_NEWBPWINDOW              40116

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40117
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
